name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  scriptresult: # id of output
    description: 'The result gotten from the python script'
runs:
  using: 'node20'
  main: 'dist/index.js'
